### ISSUE TITLE
Missing dependencies on Linux

### ISSUE THREAD

**Issue by raub** [node-3d/image-raub#1]
```
return process.dlopen(module, path._makeLong(filename));
                 ^
Error: libjpeg.so.8: cannot open shared object file: No such file or directory
```

**Comment by eard7** [comment]
Thanks @raub 
For the record, this same happens with libjbig.so.0
```
libjbig.so.0: cannot open shared object file
```
I was able to sort this out by copy/pasting the 2 files from another folder, after that worked like a charm
But maybe could be a good idea to deliver the npm package with the needed files
Thanks again!

**Comment by raub** [comment]
@eard7 Thanks for the feedback, it is really useful to know if the package works in the wild.

I added 4 more libs that seemed missing:

- libgomp.so.1
- libjbig.so.0
- liblcms2.so.2
- liblzma.so.5

Please try removing your workaround copy-files and see if clean install works for you now.

**Comment by eard7** [comment]
Thanks for the quick response @raub. Tested again by removing my workaround, deleted the node_modules from 3d-core-raub and tried ```npm i``` again. But got this error:

```
> node-gyp rebuild

module.js:550
    throw err;
    ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/home/erivera/Repos/3d-core-raub/node_modules/glfw-raub/node_modules/addon-tools-raub/index.js:8:41)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
gyp: Call to 'node -e "require('addon-tools-raub').rm()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

**Comment by raub** [comment]
@eard7 I'm glad to hear the libs are not mising anymore.

The problem with **nan** appears to be due to some NPM caching or other stuff. Usually I try to make sure **package-lock.json** is deleted along with **node_modules** before reinstalling.

By the way what is your version of NPM?

I would recomend using **npm@6.4.1** it goes together with current LTS Nodejs 10.13.0. The issue could be from an old NPM (like 4, maybe even 5), or a **package-lock.json** left by the old version. Could also be because installing from Github, but I don't want to rush the NPM release before everything works.

**Comment by eard7** [comment]
@raub thanks for the suggestion! Actually after deleting the package-lock.json (before i only deleted the node_modules folder), the nan issue disappeared. For the record, removed the node_modules and the package-lock.json, installed the dependencies again and examples run like a charm.
Currently using npm@6.4.1 with node@8.12.0 if that helps.
Thanks again, can't wait for the new version to be available @ npm
